In [1]:
# Workspace packages
from HHtobbyy.event_discrimination.DFDataset import DFDataset
from HHtobbyy.event_discrimination.Model import Model
from HHtobbyy.event_discrimination.models import map_model_to_Model
from HHtobbyy.workspace_utils.retrieval_utils import get_input_filepaths
from HHtobbyy.Categorization import Categorization

In [2]:
dfdataset_config = "/eos/uscms/store/group/lpcdihiggsboost/tsievert/HiggsDNA_parquet/DFDatasets/vManos/24_Manos_2026-04-20_12-49-04/dataset_config.json"
model, model_config = "MLP", {"output_dirpath": "/uscms/home/tsievert/nobackup/XHYbbgg/Model_Outputs/ManosMLP", "activation_func": "ELU"}
train_eras = "/uscms/home/tsievert/nobackup/XHYbbgg/HHtobbyy/configs/DFDataset_input_eras_24.txt"
test_eras = "/uscms/home/tsievert/nobackup/XHYbbgg/HHtobbyy/configs/DFDataset_input_eras_2224.txt"

dfdataset = DFDataset(dfdataset_config)
model = map_model_to_Model(model)(dfdataset, model_config)

cmslpcgpu3.fnal.gov      Fri Apr 24 14:21:38 2026  555.42.06
[0] Tesla P100-PCIE-12GB | 65°C,  99 % |  1070 / 12288 MB | tsievert(702M) tsievert(366M)


In [3]:
model.modelconfig.__dict__

{'dfdataset': <HHtobbyy.event_discrimination.DFDataset.DFDataset.DFDataset at 0x7fd6459443b0>,
 'input_size': 63,
 'output_size': 4,
 'output_dirpath': '/uscms/home/tsievert/nobackup/XHYbbgg/Model_Outputs/ManosMLP/2026-04-24_14-21-38',
 'num_layers': 5,
 'hidden_dim': 1024,
 'dropout_prob': 0.25,
 'activation_func': 'ELU',
 'class_weights': None,
 'min_delta': 0.0,
 'patience': 4,
 'monitor': 'val_loss',
 'mode': 'min',
 'accelerator': 'gpu',
 'strategy': 'auto',
 'devices': 'auto',
 'num_nodes': 1,
 'precision': '32',
 'gradient_clip_val': 10.0,
 'logger': True,
 'max_epochs': 500,
 'model_time': '2026-04-24_14-21-38'}

In [4]:
from HHtobbyy.event_discrimination.models.MLP.MLPTorch import MLPTorch

mlp_model = MLPTorch(**model.modelconfig.__dict__)

In [5]:
import torch
pth = torch.load("/uscms/home/tsievert/nobackup/XHYbbgg/Model_Outputs/ManosMLP/mlp.pth", weights_only=False)
# state_dict


In [6]:
ckpt = torch.load("/uscms/home/tsievert/nobackup/XHYbbgg/Model_Outputs/MLP/v0/2026-04-17_08-45-26/lightning_logs/version_0/checkpoints/epoch=80-step=273861.ckpt", weights_only=False)

FileNotFoundError: [Errno 2] No such file or directory: '/uscms/home/tsievert/nobackup/XHYbbgg/Model_Outputs/MLP/v0/2026-04-17_08-45-26/lightning_logs/version_0/checkpoints/epoch=80-step=273861.ckpt'

In [7]:
pth

{'epoch': 140,
 'model_state_dict': OrderedDict([('model.0.weight',
               tensor([[-0.0021, -0.0019, -0.0005,  ..., -0.0036, -0.0028,  0.0015],
                       [-0.0018, -0.0021,  0.0030,  ...,  0.0019,  0.0057, -0.0003],
                       [-0.0024,  0.0011,  0.0051,  ..., -0.0029, -0.0023, -0.0032],
                       ...,
                       [-0.0029, -0.0012,  0.0012,  ...,  0.0017, -0.0054,  0.0011],
                       [ 0.0001,  0.0047,  0.0125,  ..., -0.0012,  0.0006, -0.0028],
                       [ 0.0019,  0.0008, -0.0046,  ..., -0.0020,  0.0043,  0.0030]],
                      device='cuda:0')),
              ('model.0.bias',
               tensor([ 4.5712e-04,  1.0657e-04, -6.9500e-04,  ...,  7.0086e-05,
                       -1.1506e-03,  1.4126e-03], device='cuda:0')),
              ('model.2.weight',
               tensor([[-3.1096e-03,  2.7304e-03, -2.2563e-03,  ...,  4.4257e-03,
                        -1.8227e-04, -1.2729e-03],
     

In [9]:
ckpt

{'epoch': 80,
 'global_step': 273861,
 'pytorch-lightning_version': '2.6.1',
 'state_dict': OrderedDict([('model.0.weight',
               tensor([[ 1.8913e-02, -1.5054e-02, -8.1993e-02,  7.4426e-02, -7.7799e-03,
                        -8.8435e-03, -9.3386e-03, -5.7552e-03,  2.3713e-02,  1.5611e-02,
                         1.4844e-02,  2.1570e-01,  7.2555e-03, -2.4143e-03, -8.1254e-03,
                         4.4372e-03, -1.5602e-01, -9.8124e-04, -6.7986e-02, -7.0764e-05,
                        -2.0239e-04, -2.4814e-03, -1.0579e-01,  1.0292e-02, -1.4971e+00,
                         1.5408e-02, -4.3802e-02, -1.9825e-01,  1.2685e-02, -4.3017e-02,
                        -1.0221e+00,  5.5702e-03, -4.8412e-02, -1.1522e-01,  1.8882e-02,
                        -5.9708e-01, -8.6247e-02,  5.6042e-04, -4.2052e-02,  7.2402e-02]],
                      device='cuda:0')),
              ('model.0.bias', tensor([-0.0116], device='cuda:0')),
              ('model.2.weight', tensor([[-0.9507]], 

In [9]:
# ML packages
from torch.utils.data import DataLoader
from lightning import Trainer
from lightning.pytorch.callbacks.early_stopping import EarlyStopping

# Callbacks
callbacks = [EarlyStopping(monitor=model.modelconfig.monitor, min_delta=model.modelconfig.min_delta, patience=model.modelconfig.patience, verbose=False, mode=model.modelconfig.mode)]

trainer = Trainer(
    callbacks=callbacks,
    default_root_dir=model.modelconfig.output_dirpath,
    max_epochs=model.modelconfig.max_epochs, 
    accelerator=model.modelconfig.accelerator,
    strategy=model.modelconfig.strategy,
    num_nodes=model.modelconfig.num_nodes,
    precision=model.modelconfig.precision, 
    gradient_clip_val=model.modelconfig.gradient_clip_val,
    logger=model.modelconfig.logger,
    devices=1 if eval else model.modelconfig.devices,
)

mlp_model.load_state_dict(pth['model_state_dict'])
trainer.predict(mlp_model, DataLoader([]))
trainer.save_checkpoint("manos_trained_model.ckpt")

mlp_model.load_state_dict(pth['best_weights'])
trainer.predict(mlp_model, DataLoader([]))
trainer.save_checkpoint("manos_best_model.ckpt")

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
/uscms/home/tsievert/nobackup/XHYbbgg/bbyy_venv/lib/python3.12/site-packages/lightning/pytorch/trainer/connectors/logger_connector/logger_connector.py:76: Starting from v1.9.0, `tensorboardX` has been removed as a dependency of the `lightning.pytorch` package, due to potential conflicts with other packages in the ML ecosystem. For this reason, `logger=True` will use `CSVLogger` as the default logger, unless the `tensorboard` or `tensorboardX` packages are found. Please `pip install lightning[extra]` or one of them to enable TensorBoard support by default
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitMo

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
/uscms/home/tsievert/nobackup/XHYbbgg/bbyy_venv/lib/python3.12/site-packages/lightning/pytorch/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
/uscms/home/tsievert/nobackup/XHYbbgg/bbyy_venv/lib/python3.12/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:434: The 'predict_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/uscms/home/tsievert/nobackup/XHYbbgg/bbyy_venv/lib/python3.12/site-packages/lightning/pytorch/utilities/data.py:106: Total length of `DataLoader` across ranks is zero. Please make sure this was your intention.
`weights_only` was not set, defaulting to `False`.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
`weights_only` was not set, defaulting to `False`.


In [13]:
pthckpt = torch.load("manos_trained_model.ckpt", weights_only=False)

In [14]:
pthckpt

{'epoch': 0,
 'global_step': 0,
 'pytorch-lightning_version': '2.6.1',
 'state_dict': OrderedDict([('model.0.weight',
               tensor([[-0.0021, -0.0019, -0.0005,  ..., -0.0036, -0.0028,  0.0015],
                       [-0.0018, -0.0021,  0.0030,  ...,  0.0019,  0.0057, -0.0003],
                       [-0.0024,  0.0011,  0.0051,  ..., -0.0029, -0.0023, -0.0032],
                       ...,
                       [-0.0029, -0.0012,  0.0012,  ...,  0.0017, -0.0054,  0.0011],
                       [ 0.0001,  0.0047,  0.0125,  ..., -0.0012,  0.0006, -0.0028],
                       [ 0.0019,  0.0008, -0.0046,  ..., -0.0020,  0.0043,  0.0030]])),
              ('model.0.bias',
               tensor([ 4.5712e-04,  1.0657e-04, -6.9500e-04,  ...,  7.0086e-05,
                       -1.1506e-03,  1.4126e-03])),
              ('model.2.weight',
               tensor([[-3.1096e-03,  2.7304e-03, -2.2563e-03,  ...,  4.4257e-03,
                        -1.8227e-04, -1.2729e-03],
           